PhoneBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from back.profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    path('', include('back.profiles.urls')),
    # path('companies/', include('back.companies.urls')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/profiles/urls.py
from django.urls import path, include
from back.profiles import views


urlpatterns = [
    path('', views.UserListView.as_view(), name='user-list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
]

back/companies/models.py
import uuid
import re
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

from back.profiles.models import User, PhoneNumber


class Organization(models.Model):
    name = models.CharField(_("Имя"), max_length=65)
    # office = models.ForeignKey(
    #     'Office',
    #     on_delete=models.SET_NULL,
    #     null=True, blank=True,
    #     verbose_name=_("Офис")
    # )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Организация")
        verbose_name_plural = _("Организация")


class Office(models.Model):
    firm = models.ForeignKey(
            'Organization',
            on_delete=models.SET_NULL,
            null=True, blank=True,
            verbose_name=_("Организация")
        )
    employee = models.ManyToManyField(
        User,
        # on_delete=models.SET_NULL,
        # null=True,
        # blank=True,
        verbose_name=_("Сотрудник")
    )
    # phone = models.ForeignKey(
    #     PhoneNumber,
    #     on_delete=models.CASCADE,
    #     verbose_name=_("Телефон")
    # )
    # firm = models.CharField(
    #     max_length=240,
    #     null=True, blank=True,
    #     verbose_name=_("Организация")
    # )
    address = models.CharField(_("Адрес"), max_length=65, blank=True, null=True)
    room = models.PositiveSmallIntegerField(_("Кабинет"))

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = _("Офис")
        verbose_name_plural = _("Офисы")

back/profiles/models.py
from django.db import models
from django.contrib.auth.models import (
    PermissionsMixin,
    BaseUserManager,
    AbstractBaseUser,
    Permission,
    Group
)
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.dispatch import receiver

import uuid

from back.permissions.choices import *


def get_default_uuid():
    return uuid.uuid4().hex


class UserManager(BaseUserManager):
    def create_user(self,
                    position,
                    email,
                    birthday,
                    full_name,
                    avatar,
                    bio,
                    accepted_tos=None,
                    is_active=True,
                    password=None
                    ):
        if not accepted_tos:
            raise ValueError(_("Пользователи должны принять соглашение  "))

        user = self.model(
            email=self.normalize_email(email),
            position=position,
            avatar=avatar,
            birthday=birthday,
            full_name=full_name,
            bio=bio,
            accepted_tos=True,
            is_active=is_active
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self,
                         email,
                         # birthday,
                         password,
                         # position,
                         full_name,
                         # bio,
                         ):
        user = self.create_user(
            email,
            # position,
            full_name,
            # birthday,
            # bio,
            accepted_tos=True,
            password=password
        )
        user.is_staff = True
        user.is_superuser = True
        # try:
        #     admins = Group.objects.get(name__iexact="Администраторы")
        # except Group.DoesNotExist:
        #     admins = Group.objects.create(name="Администраторы")
        # admins.permissions.add(
        #     Permission.objects.get(ADMINS_PERMISSIONS))
        # user.groups.add(admins)
        user.save()
        return user

    def create_employee(self, email, birthday, password, position, full_name, bio,):
        user = self.create_user(
            email,
            birthday,
            password,
            position,
            full_name,
            bio,
            accepted_tos=True,
            password=password,
        )
        try:
            employee = Group.objects.get(name__iexact="Сотрудники")
        except Group.DoesNotExist:
            employee = Group.objects.create(name="Сотрудники")

        employee.permissions.add(
            Permission.objects.get(MEMBERS_PERMISSIONS))  # add can_give_discount permission
        user.groups.add(employee)
        user.save()
        return user


DEFAULT_IMAGE = 'static/media/default.jpg'


class User(AbstractBaseUser, PermissionsMixin):
    # phone = models.ForeignKey(PhoneNumber, on_delete=models.SET_NULL, null=True, blank=True)
    position = models.CharField(max_length=122, null=True, blank=True, verbose_name=_("Должность"))
    uuid = models.CharField(_("UUID"), max_length=32, editable=False, null=False,
                            blank=False, unique=True, default=get_default_uuid)
    email = models.EmailField(_("Имейл"), max_length=125, unique=True)
    full_name = models.CharField(_("Ф.И.О."), max_length=120)
    avatar = models.ImageField(_("Изображение"), upload_to='avatars/', default=DEFAULT_IMAGE, null=True, blank=True)
    bio = models.TextField(_("О пользователе"), max_length=300, null=True, blank=True)
    birthday = models.DateField(_("День рождения"), null=True, blank=True)
    accepted_tos = models.BooleanField(default=True, verbose_name=_("Принято соглашение"))
    is_active = models.BooleanField(_("Активен"), default=True)
    is_admin = models.BooleanField(_("Админ"), default=False)
    created_at = models.DateTimeField(_("Создан"), auto_now_add=True, auto_now=False, editable=False)
    updated_at = models.DateTimeField(_("Обновлен"), auto_now_add=False, auto_now=True, editable=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["full_name"]

    def __str__(self):
        return "%s. %s" % (self.id, self.full_name)

    class Meta:
        ordering = ["full_name"]
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")

    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])

    def is_staff(self):
        return self.is_admin

    def image_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return DEFAULT_IMAGE
    # def set_image_to_default(self):
    #     self.image.delete(save=False)  # delete old image file
    #     self.image = DEFAULT_IMAGE
    #     self.save()

    def get_short_name(self):
        l = self.full_name.split(' ')[1:2]
        name = ''.join(l)
        return name


class PhoneNumber(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, null=True, blank=True, verbose_name=_("Пользователь"))
    phone_mobile = models.CharField(_("Мобильный тел."), max_length=26, null=True, blank=True)
    phone_small = models.PositiveSmallIntegerField(_("Короткий номер"), null=True, blank=True)
    phone_city = models.PositiveIntegerField(_("Городской номер"), null=True, blank=True)

    def __str__(self):
        return "%s, %s" % (self.phone_city, self.phone_small)

    class Meta:
        verbose_name = _("Номер телефона")
        verbose_name_plural = _("Номера телефонов")

back/profiles/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from back.profiles.models import User


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label=_('Пароль'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Повторите пароль'), widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name','email', 'birthday', 'position')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Пароли не совпадают"))
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'birthday', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

back/profiles/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from back.profiles.models import User, PhoneNumber
from back.companies.models import Office
# Create your views here.


class UserListView(ListView):
    model = User
    paginate_by = 8

    def get_queryset(self):
        return User.objects.filter(is_active=True)


class UserDetailView(DetailView):
    model = User

templates/profiles/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="container-fluid">
    <h2 class="center h1">Список пользователей</h2>
    <!-- begin cards -->
    <div class="cards">
        {% for profile in user_list %}
        <!-- begin ll -->
        <div class="ll">
            <div class="card blue-hover">
                <div class="card-item">
                    <img class="card-img" src="{{ profile.image_url }}"></img>
                    <div class="text-card-cont">
                        <div class="mr-grid">
                            <div class="col1">
                                <h2>{{ profile.full_name }}</h2>
                                <ul class="card-gen">
                                    <li>{{ profile.position }}</li>
{#                                    {% for office in profile.office_set.all %}#}
{#                                        <li>{{ office }}/</li>#}
{#                                        <li class="card-gen-room">к {{ office.room }}</li>#}
{#                                    {% endfor %}#}
                                </ul>
                            </div>
                        </div>
                        <div class="mr-grid summary-row">
                            <div class="col2">
                            {% for company in profile.office_set.all %}
                                <h5>{{ company.firm }}</h5>
                            {% endfor %}

                            </div>
                            <div class="col2">
                                <ul class="card-likes">
                                    <li>{{ profile.birthday }}</li>
{#                                    <li><i class="material-icons">&#xE813;</i>124</li>#}
{#                                    <li><i class="material-icons">&#xE813;</i>3</li>#}
                                </ul>
                            </div>
                        </div>
                        <div class="mr-grid">
                            <div class="col1">
                                <p class="card-description">{{ profile.bio|truncatechars:400 }} </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mr-grid actors-row">
                    <div class="col1">
                        <p class="card-actors">{% for phone in profile.phonenumber_set.all %}
                            <span>{{ phone.phone_mobile }}</span>
                            <span>{{ phone.phone_city }}</span>
                            <span>{{ phone.phone_small }}</span>
                        {% endfor %}
                        </p>
                    </div>
                </div>
                <div class="mr-grid action-row">
                    <div class="col2">
                        <div class="watch-btn"><h3><i class="material-icons">&#xE037;</i>Позвонить</h3></div>
                    </div>
                    <div class="col6 action-btn"><i class="material-icons">&#xE161;</i>
                    </div>
                    <div class="col6 action-btn"><i class="material-icons">&#xE866;</i>
                    </div>
                    <div class="col6 action-btn"><i class="material-icons">&#xE80D;</i>
                    </div>
                </div>
            </div>
        </div>
        <!-- end ll -->
        {% endfor %}
    </div>
</section>
{% endblock %}